version: '3.8'
services:
  db:
    image: postgres
    container_name: db
    ports: 
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: reservation_app
      TZ: Asia/Tokyo
    restart: always

  server:
    build: .
    container_name: server
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "30000:3000"
      - "30001:30001"
    depends_on:
      - db
    environment: 
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - JWT_SECRET_KEY=test # ここは本番環境では絶対に変更すること
      - CLIENT_HOST=http://localhost:3000
    restart: always